export const GET_NAME_PRODUCT = "GET_NAME_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const ORDER_ALPHABETICAL = "ORDER_ALPHABETICAL";
export const ORDER_PRICE = "ORDER_PRICE";
export const GET_DETAIL = "GET_DETAIL";
export const GET_PRODUCT_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY"
