export const GET_USER_LOGIN = "GET_USER_LOGIN";
export const CLEAN_USER_LOGIN = "CLEAN_USER_LOGIN";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ONE_USER_DETAIL = "GET_ONE_USER_DETAIL";
export const CLEAN_USER_DETAIL = "CLEAN_USER_DETAIL";
