export const GET_PRODUCT_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const CATEGORY_DETAIL = "CATEGORY_DETAIL";
export const CLEAN_CAT_DETAIL = "CLEAN_CAT_DETAIL";